name: CI/CD

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

env:
  USER: loganmarchione
  REPO: docker-php-startpage

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Setup PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: '8.4'
        tools: phpstan, phpstan/phpstan-deprecation-rules

    - name: Install dependencies
      run: composer install --no-interaction --no-plugins --no-scripts --no-dev --prefer-dist --no-ansi --no-progress           

    - name: Run PHPStan
      run: phpstan analyse --level 7 index.php

    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        failure-threshold: error
        ignore: DL3008,DL3018

    # - name: PHP Compatibility
    #   uses: pantheon-systems/phpcompatibility-action@v1
    #   with:
    #     skip-php-setup: true
    #     test-versions: 7.4-
    #     paths: ${{ github.workspace }}

  ci:
    name: Build and test

    needs: lint
    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

    - name: Build Docker Image
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        push: false
        context: .
        file: Dockerfile
        load: true
        tags: |
          ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}
          ${{ env.USER }}/${{ env.REPO }}:latest

    - name: Test image
      run: |
        docker images
        docker run --name test-container --detach ${USER}/${REPO}:${VERSION}
        docker ps -a

    - name: Container scan with Dockle
      uses: goodwithtech/dockle-action@e30e6af832aad6ea7dca2a248d31a85eab6dbd68 # v0.4.15
      with:
        image: '${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}'
        format: 'list'
        exit-code: '1'
        exit-level: 'warn'
        ignore: 'CIS-DI-0001,CIS-DI-0010'

    # - name: Container scan with Trivy
    #   uses: aquasecurity/trivy-action@0.35.0
    #   with:
    #     scan-type: 'image'
    #     image-ref: '${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}'
    #     trivy-config: ./github/trivy.yaml

  cd:
    name: Deploy

    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

    - name: Login to DockerHub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Build Docker Image
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        push: true
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: |
          ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}
          ${{ env.USER }}/${{ env.REPO }}:latest
